### PR TITLE
upipe_v210: fix compilation without asm

### PR DESCRIPTION
**Pull request by quarium**

### CODE REVIEW

**Comment by kierank** [comment]
lgtm

**Comment by quarium** [comment]
The diff in hbrmt is useless, i'll remove it

**Comment by funman** [comment]
And the changes in configure.ac, isn't it separate too ?

**Comment by quarium** [comment]
Without the change in configure.ac HAVE_X86ASM is always defined

**Comment by funman** [comment]
Ah ok, that's fine then I had not fully understood the issue

**Pull request merged**
