### PR TITLE
Move some C functions into dedicated files

### PR DESCRIPTION
**Pull request by JDarnley**
At the request of @nto I have cherry-picked these commits from the checkasm pull request.

### CODE REVIEW

**Comment by cmassiot** [comment]
Your license header only speaks of ffmpeg, shouldn't it be changed to Upipe ? Especially since some functions cannot possibly originate from ffmpeg.

**Comment by JDarnley** [comment]
Hm.  You might be right.  I just duplicated the existing files and removed the parts as needed.  The licenses on the new files in upipe-hbrmt could be changed, maybe.  Do you want me to do that?

**Comment by cmassiot** [comment]
Yes please

**Comment by JDarnley** [comment]
@cmassiot @nto  I made the license header changes a few days ago.  Do you have any more comments?

**Comment by nto** [comment]
v210enc.c and v210dec.c still shows the ffmpeg license notice. Apparently it's the case for some older files as well, so maybe they all need to be changed in a separate pull request. It's definitely misleading to say "You should have received a copy of the GNU Lesser General Public License along with FFmpeg" in these files.

**Comment by JDarnley** [comment]
Yes, I didn't change those files because of this line in the header "This file is based on the implementation in FFmpeg".  FFmpeg does have a v210 codec so these functions are likely to be derived from them.

I only moved the functions from one file to another so I shouldn't be changing what license they have (in my understanding of these things).  I probably shouldn't change the license headers on the 10-bit sdi packing either but you could argue that the header was wrong since the beginning in commit 9a54a727

If you think I should change the named library (FFmpeg) in the new v210 files I will.

**Comment by nto** [comment]
The license and authorship informations is a real mess right now in Upipe. We can apply this pull request now so you can move on to the checkasm patch. We will review the license notices situation later.

**Pull request merged**
